package Hibernate;
// Generated 27 mars 2013 14:02:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attribution generated by hbm2java
 */
@Entity
@Table(name="ATTRIBUTION"
    ,schema="USR_VIVIEN"
)
public class Attribution  implements java.io.Serializable {


     private AttributionId id;
     private Groupe groupe;
     private Offre offre;
     private BigDecimal nombrechambres;

    public Attribution() {
    }

    public Attribution(AttributionId id, Groupe groupe, Offre offre, BigDecimal nombrechambres) {
       this.id = id;
       this.groupe = groupe;
       this.offre = offre;
       this.nombrechambres = nombrechambres;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idetab", column=@Column(name="IDETAB", nullable=false, length=8) ), 
        @AttributeOverride(name="idtypechambre", column=@Column(name="IDTYPECHAMBRE", nullable=false, length=2) ), 
        @AttributeOverride(name="idgroupe", column=@Column(name="IDGROUPE", nullable=false, length=4) ) } )
    public AttributionId getId() {
        return this.id;
    }
    
    public void setId(AttributionId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDGROUPE", nullable=false, insertable=false, updatable=false)
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="IDETAB", referencedColumnName="IDETAB", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDTYPECHAMBRE", referencedColumnName="IDTYPECHAMBRE", nullable=false, insertable=false, updatable=false) } )
    public Offre getOffre() {
        return this.offre;
    }
    
    public void setOffre(Offre offre) {
        this.offre = offre;
    }
    
    @Column(name="NOMBRECHAMBRES", nullable=false, precision=22, scale=0)
    public BigDecimal getNombrechambres() {
        return this.nombrechambres;
    }
    
    public void setNombrechambres(BigDecimal nombrechambres) {
        this.nombrechambres = nombrechambres;
    }




}


