package Hibernate;
// Generated 27 mars 2013 14:02:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttributionId generated by hbm2java
 */
@Embeddable
public class AttributionId  implements java.io.Serializable {


     private String idetab;
     private String idtypechambre;
     private String idgroupe;

    public AttributionId() {
    }

    public AttributionId(String idetab, String idtypechambre, String idgroupe) {
       this.idetab = idetab;
       this.idtypechambre = idtypechambre;
       this.idgroupe = idgroupe;
    }
   

    @Column(name="IDETAB", nullable=false, length=8)
    public String getIdetab() {
        return this.idetab;
    }
    
    public void setIdetab(String idetab) {
        this.idetab = idetab;
    }

    @Column(name="IDTYPECHAMBRE", nullable=false, length=2)
    public String getIdtypechambre() {
        return this.idtypechambre;
    }
    
    public void setIdtypechambre(String idtypechambre) {
        this.idtypechambre = idtypechambre;
    }

    @Column(name="IDGROUPE", nullable=false, length=4)
    public String getIdgroupe() {
        return this.idgroupe;
    }
    
    public void setIdgroupe(String idgroupe) {
        this.idgroupe = idgroupe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AttributionId) ) return false;
		 AttributionId castOther = ( AttributionId ) other; 
         
		 return ( (this.getIdetab()==castOther.getIdetab()) || ( this.getIdetab()!=null && castOther.getIdetab()!=null && this.getIdetab().equals(castOther.getIdetab()) ) )
 && ( (this.getIdtypechambre()==castOther.getIdtypechambre()) || ( this.getIdtypechambre()!=null && castOther.getIdtypechambre()!=null && this.getIdtypechambre().equals(castOther.getIdtypechambre()) ) )
 && ( (this.getIdgroupe()==castOther.getIdgroupe()) || ( this.getIdgroupe()!=null && castOther.getIdgroupe()!=null && this.getIdgroupe().equals(castOther.getIdgroupe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdetab() == null ? 0 : this.getIdetab().hashCode() );
         result = 37 * result + ( getIdtypechambre() == null ? 0 : this.getIdtypechambre().hashCode() );
         result = 37 * result + ( getIdgroupe() == null ? 0 : this.getIdgroupe().hashCode() );
         return result;
   }   


}


