package Hibernate;
// Generated 27 mars 2013 14:02:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etablissement generated by hbm2java
 */
@Entity
@Table(name="ETABLISSEMENT"
    ,schema="USR_VIVIEN"
)
public class Etablissement  implements java.io.Serializable {


     private String id;
     private String nom;
     private String adresserue;
     private String codepostal;
     private String ville;
     private String tel;
     private String adresseelectronique;
     private BigDecimal type;
     private String civiliteresponsable;
     private String nomresponsable;
     private String prenomresponsable;
     private Set offres = new HashSet(0);

    public Etablissement() {
    }

	
    public Etablissement(String id, String nom, String adresserue, String codepostal, String ville, String tel, BigDecimal type, String civiliteresponsable, String nomresponsable) {
        this.id = id;
        this.nom = nom;
        this.adresserue = adresserue;
        this.codepostal = codepostal;
        this.ville = ville;
        this.tel = tel;
        this.type = type;
        this.civiliteresponsable = civiliteresponsable;
        this.nomresponsable = nomresponsable;
    }
    public Etablissement(String id, String nom, String adresserue, String codepostal, String ville, String tel, String adresseelectronique, BigDecimal type, String civiliteresponsable, String nomresponsable, String prenomresponsable, Set offres) {
       this.id = id;
       this.nom = nom;
       this.adresserue = adresserue;
       this.codepostal = codepostal;
       this.ville = ville;
       this.tel = tel;
       this.adresseelectronique = adresseelectronique;
       this.type = type;
       this.civiliteresponsable = civiliteresponsable;
       this.nomresponsable = nomresponsable;
       this.prenomresponsable = prenomresponsable;
       this.offres = offres;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, length=8)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="NOM", nullable=false, length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    
    @Column(name="ADRESSERUE", nullable=false, length=45)
    public String getAdresserue() {
        return this.adresserue;
    }
    
    public void setAdresserue(String adresserue) {
        this.adresserue = adresserue;
    }
    
    @Column(name="CODEPOSTAL", nullable=false, length=5)
    public String getCodepostal() {
        return this.codepostal;
    }
    
    public void setCodepostal(String codepostal) {
        this.codepostal = codepostal;
    }
    
    @Column(name="VILLE", nullable=false, length=35)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    
    @Column(name="TEL", nullable=false, length=13)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    
    @Column(name="ADRESSEELECTRONIQUE", length=70)
    public String getAdresseelectronique() {
        return this.adresseelectronique;
    }
    
    public void setAdresseelectronique(String adresseelectronique) {
        this.adresseelectronique = adresseelectronique;
    }
    
    @Column(name="TYPE", nullable=false, precision=22, scale=0)
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    
    @Column(name="CIVILITERESPONSABLE", nullable=false, length=12)
    public String getCiviliteresponsable() {
        return this.civiliteresponsable;
    }
    
    public void setCiviliteresponsable(String civiliteresponsable) {
        this.civiliteresponsable = civiliteresponsable;
    }
    
    @Column(name="NOMRESPONSABLE", nullable=false, length=25)
    public String getNomresponsable() {
        return this.nomresponsable;
    }
    
    public void setNomresponsable(String nomresponsable) {
        this.nomresponsable = nomresponsable;
    }
    
    @Column(name="PRENOMRESPONSABLE", length=25)
    public String getPrenomresponsable() {
        return this.prenomresponsable;
    }
    
    public void setPrenomresponsable(String prenomresponsable) {
        this.prenomresponsable = prenomresponsable;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etablissement")
    public Set getOffres() {
        return this.offres;
    }
    
    public void setOffres(Set offres) {
        this.offres = offres;
    }




}


