package Hibernate;
// Generated 27 mars 2013 14:02:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name="GROUPE"
    ,schema="USR_VIVIEN"
)
public class Groupe  implements java.io.Serializable {


     private String id;
     private String nom;
     private String identiteresponsable;
     private String adressepostale;
     private BigDecimal nombrepersonnes;
     private String nompays;
     private char hebergement;
     private Set attributions = new HashSet(0);

    public Groupe() {
    }

	
    public Groupe(String id, String nom, BigDecimal nombrepersonnes, String nompays, char hebergement) {
        this.id = id;
        this.nom = nom;
        this.nombrepersonnes = nombrepersonnes;
        this.nompays = nompays;
        this.hebergement = hebergement;
    }
    public Groupe(String id, String nom, String identiteresponsable, String adressepostale, BigDecimal nombrepersonnes, String nompays, char hebergement, Set attributions) {
       this.id = id;
       this.nom = nom;
       this.identiteresponsable = identiteresponsable;
       this.adressepostale = adressepostale;
       this.nombrepersonnes = nombrepersonnes;
       this.nompays = nompays;
       this.hebergement = hebergement;
       this.attributions = attributions;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, length=4)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="NOM", nullable=false, length=40)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    
    @Column(name="IDENTITERESPONSABLE", length=40)
    public String getIdentiteresponsable() {
        return this.identiteresponsable;
    }
    
    public void setIdentiteresponsable(String identiteresponsable) {
        this.identiteresponsable = identiteresponsable;
    }
    
    @Column(name="ADRESSEPOSTALE", length=120)
    public String getAdressepostale() {
        return this.adressepostale;
    }
    
    public void setAdressepostale(String adressepostale) {
        this.adressepostale = adressepostale;
    }
    
    @Column(name="NOMBREPERSONNES", nullable=false, precision=22, scale=0)
    public BigDecimal getNombrepersonnes() {
        return this.nombrepersonnes;
    }
    
    public void setNombrepersonnes(BigDecimal nombrepersonnes) {
        this.nombrepersonnes = nombrepersonnes;
    }
    
    @Column(name="NOMPAYS", nullable=false, length=40)
    public String getNompays() {
        return this.nompays;
    }
    
    public void setNompays(String nompays) {
        this.nompays = nompays;
    }
    
    @Column(name="HEBERGEMENT", nullable=false, length=1)
    public char getHebergement() {
        return this.hebergement;
    }
    
    public void setHebergement(char hebergement) {
        this.hebergement = hebergement;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="groupe")
    public Set getAttributions() {
        return this.attributions;
    }
    
    public void setAttributions(Set attributions) {
        this.attributions = attributions;
    }




}


