package Hibernate;
// Generated 27 mars 2013 14:02:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OffreId generated by hbm2java
 */
@Embeddable
public class OffreId  implements java.io.Serializable {


     private String idetab;
     private String idtypechambre;

    public OffreId() {
    }

    public OffreId(String idetab, String idtypechambre) {
       this.idetab = idetab;
       this.idtypechambre = idtypechambre;
    }
   

    @Column(name="IDETAB", nullable=false, length=8)
    public String getIdetab() {
        return this.idetab;
    }
    
    public void setIdetab(String idetab) {
        this.idetab = idetab;
    }

    @Column(name="IDTYPECHAMBRE", nullable=false, length=2)
    public String getIdtypechambre() {
        return this.idtypechambre;
    }
    
    public void setIdtypechambre(String idtypechambre) {
        this.idtypechambre = idtypechambre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OffreId) ) return false;
		 OffreId castOther = ( OffreId ) other; 
         
		 return ( (this.getIdetab()==castOther.getIdetab()) || ( this.getIdetab()!=null && castOther.getIdetab()!=null && this.getIdetab().equals(castOther.getIdetab()) ) )
 && ( (this.getIdtypechambre()==castOther.getIdtypechambre()) || ( this.getIdtypechambre()!=null && castOther.getIdtypechambre()!=null && this.getIdtypechambre().equals(castOther.getIdtypechambre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdetab() == null ? 0 : this.getIdetab().hashCode() );
         result = 37 * result + ( getIdtypechambre() == null ? 0 : this.getIdtypechambre().hashCode() );
         return result;
   }   


}


