package Hibernate;
// Generated 27 mars 2013 14:02:55 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typechambre generated by hbm2java
 */
@Entity
@Table(name="TYPECHAMBRE"
    ,schema="USR_VIVIEN"
)
public class Typechambre  implements java.io.Serializable {


     private String id;
     private String libelle;
     private Set offres = new HashSet(0);

    public Typechambre() {
    }

	
    public Typechambre(String id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }
    public Typechambre(String id, String libelle, Set offres) {
       this.id = id;
       this.libelle = libelle;
       this.offres = offres;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, length=2)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="LIBELLE", nullable=false, length=15)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="typechambre")
    public Set getOffres() {
        return this.offres;
    }
    
    public void setOffres(Set offres) {
        this.offres = offres;
    }




}


